// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Shader Graphs/Galaxy_Render" {
Properties {
 Vector2_CA89079F ("Boss_DIstance", Vector) = (1.000000,1.000000,0.000000,0.000000)
[NoScaleOffset] [NonModifiableTextureData]  _Texture2DAsset_6A51C40B_Out ("Texture2D", 2D) = "white" { }
}
SubShader { 
 Tags { "QUEUE"="Geometry+0" "RenderType"="Opaque" "RenderPipeline"="LightweightPipeline" }


 // Stats for Vertex shader:
 //        d3d11: 44 math
 // Stats for Fragment shader:
 //        d3d11: 13 math, 1 texture
 Pass {
  Name "StandardUnlit"
  Tags { "LIGHTMODE"="LightweightForward" "QUEUE"="Geometry+0" "RenderType"="Opaque" "RenderPipeline"="LightweightPipeline" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
No keywords set in this variant.
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 44 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerCamera" (144 bytes) on slot 0 {
  Vector3 _WorldSpaceCameraPos at 64
  Vector4 _ProjectionParams at 80
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (416 bytes) on slot 2 {
  Matrix4x4 unity_MatrixVP at 304
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 3   xyz         1     NONE   float   xyz 
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float   xyz 
// TEXCOORD                 6   xyz         4     NONE   float   xyz 
// TEXCOORD                 7   xyz         5     NONE   float   xyz 
// TEXCOORD                 8   xyzw        6     NONE   float   xyzw
// TEXCOORD                 9   xyzw        7     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[6], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[23], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyzw
      dcl_output o7.xyzw
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
   4: add r0.xyz, r0.xyzx, cb1[3].xyzx
   5: add o5.xyz, -r0.xyzx, cb0[4].xyzx
   6: mul r0.xyz, r1.yyyy, cb1[5].xyzx
   7: mad r0.xyz, cb1[4].xyzx, r1.xxxx, r0.xyzx
   8: mad r0.xyz, cb1[6].xyzx, r1.zzzz, r0.xyzx
   9: mov o1.xyz, r1.xyzx
  10: add r0.xyz, r0.xyzx, cb1[7].xyzx
  11: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
  12: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
  13: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
  14: add r0.xyzw, r0.xyzw, cb1[3].xyzw
  15: mul r1.xyzw, r0.yyyy, cb2[20].xyzw
  16: mad r1.xyzw, cb2[19].xyzw, r0.xxxx, r1.xyzw
  17: mad r1.xyzw, cb2[21].xyzw, r0.zzzz, r1.xyzw
  18: mad o0.xyzw, cb2[22].xyzw, r0.wwww, r1.xyzw
  19: dp3 r0.x, v1.xyzx, cb1[4].xyzx
  20: dp3 r0.y, v1.xyzx, cb1[5].xyzx
  21: dp3 r0.z, v1.xyzx, cb1[6].xyzx
  22: dp3 r0.w, r0.xyzx, r0.xyzx
  23: rsq r0.w, r0.w
  24: mul r0.xyz, r0.wwww, r0.xyzx
  25: mov o2.xyz, r0.xyzx
  26: mul r1.xyz, v2.yyyy, cb1[1].xyzx
  27: mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
  28: mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
  29: dp3 r0.w, r1.xyzx, r1.xyzx
  30: rsq r0.w, r0.w
  31: mul r1.xyz, r0.wwww, r1.xyzx
  32: mov o3.xyz, r1.xyzx
  33: mul r2.xyz, r0.zxyz, r1.yzxy
  34: mad r0.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
  35: mul o4.xyz, r0.xyzx, v2.wwww
  36: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
  37: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
  38: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
  39: mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
  40: mul r1.xyzw, r0.yyyy, cb2[20].xyzw
  41: mad r1.xyzw, cb2[19].xyzw, r0.xxxx, r1.xyzw
  42: mad r1.xyzw, cb2[21].xyzw, r0.zzzz, r1.xyzw
  43: mad r0.xyzw, cb2[22].xyzw, r0.wwww, r1.xyzw
  44: mul r0.y, r0.y, cb0[5].x
  45: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
  46: mov o6.zw, r0.zzzw
  47: add o6.xy, r1.zzzz, r1.xwxx
  48: mov o7.xyzw, v3.xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 13 math, 2 temp registers, 1 textures
Set 2D Texture "_Texture2DAsset_6A51C40B_Out" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 3   xyz         1     NONE   float       
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float       
// TEXCOORD                 6   xyz         4     NONE   float       
// TEXCOORD                 7   xyz         5     NONE   float   xyz 
// TEXCOORD                 8   xyzw        6     NONE   float   xy w
// TEXCOORD                 9   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v5.xyz
      dcl_input_ps linear v6.xyw
      dcl_output o0.xyzw
      dcl_temps 2
   0: dp3 r0.x, v2.xyzx, v2.xyzx
   1: rsq r0.x, r0.x
   2: mul r0.xyz, r0.xxxx, v2.xyzx
   3: dp3 r0.w, v5.xyzx, v5.xyzx
   4: rsq r0.w, r0.w
   5: mul r1.xyz, r0.wwww, v5.xyzx
   6: dp3_sat r0.x, r0.xyzx, r1.xyzx
   7: add r0.x, -r0.x, l(1.000000)
   8: log r0.x, r0.x
   9: mul r0.x, r0.x, l(7.000000)
  10: exp r0.x, r0.x
  11: div r0.yz, v6.xxyx, v6.wwww
  12: sample r1.xyzw, r0.yzyy, t0.xyzw, s0
  13: mad o0.xyz, r0.xxxx, l(1.222693, 0.000000, 3.679245, 0.000000), r1.xyzx
  14: mov o0.w, l(1.000000)
  15: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords set in this variant: DIRLIGHTMAP_COMBINED 
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 44 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerCamera" (144 bytes) on slot 0 {
  Vector3 _WorldSpaceCameraPos at 64
  Vector4 _ProjectionParams at 80
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (416 bytes) on slot 2 {
  Matrix4x4 unity_MatrixVP at 304
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 3   xyz         1     NONE   float   xyz 
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float   xyz 
// TEXCOORD                 6   xyz         4     NONE   float   xyz 
// TEXCOORD                 7   xyz         5     NONE   float   xyz 
// TEXCOORD                 8   xyzw        6     NONE   float   xyzw
// TEXCOORD                 9   xyzw        7     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[6], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[23], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyz
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyzw
      dcl_output o7.xyzw
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   1: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   3: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
   4: add r0.xyz, r0.xyzx, cb1[3].xyzx
   5: add o5.xyz, -r0.xyzx, cb0[4].xyzx
   6: mul r0.xyz, r1.yyyy, cb1[5].xyzx
   7: mad r0.xyz, cb1[4].xyzx, r1.xxxx, r0.xyzx
   8: mad r0.xyz, cb1[6].xyzx, r1.zzzz, r0.xyzx
   9: mov o1.xyz, r1.xyzx
  10: add r0.xyz, r0.xyzx, cb1[7].xyzx
  11: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
  12: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
  13: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
  14: add r0.xyzw, r0.xyzw, cb1[3].xyzw
  15: mul r1.xyzw, r0.yyyy, cb2[20].xyzw
  16: mad r1.xyzw, cb2[19].xyzw, r0.xxxx, r1.xyzw
  17: mad r1.xyzw, cb2[21].xyzw, r0.zzzz, r1.xyzw
  18: mad o0.xyzw, cb2[22].xyzw, r0.wwww, r1.xyzw
  19: dp3 r0.x, v1.xyzx, cb1[4].xyzx
  20: dp3 r0.y, v1.xyzx, cb1[5].xyzx
  21: dp3 r0.z, v1.xyzx, cb1[6].xyzx
  22: dp3 r0.w, r0.xyzx, r0.xyzx
  23: rsq r0.w, r0.w
  24: mul r0.xyz, r0.wwww, r0.xyzx
  25: mov o2.xyz, r0.xyzx
  26: mul r1.xyz, v2.yyyy, cb1[1].xyzx
  27: mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
  28: mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
  29: dp3 r0.w, r1.xyzx, r1.xyzx
  30: rsq r0.w, r0.w
  31: mul r1.xyz, r0.wwww, r1.xyzx
  32: mov o3.xyz, r1.xyzx
  33: mul r2.xyz, r0.zxyz, r1.yzxy
  34: mad r0.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
  35: mul o4.xyz, r0.xyzx, v2.wwww
  36: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
  37: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
  38: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
  39: mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
  40: mul r1.xyzw, r0.yyyy, cb2[20].xyzw
  41: mad r1.xyzw, cb2[19].xyzw, r0.xxxx, r1.xyzw
  42: mad r1.xyzw, cb2[21].xyzw, r0.zzzz, r1.xyzw
  43: mad r0.xyzw, cb2[22].xyzw, r0.wwww, r1.xyzw
  44: mul r0.y, r0.y, cb0[5].x
  45: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
  46: mov o6.zw, r0.zzzw
  47: add o6.xy, r1.zzzz, r1.xwxx
  48: mov o7.xyzw, v3.xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 13 math, 2 temp registers, 1 textures
Set 2D Texture "_Texture2DAsset_6A51C40B_Out" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 3   xyz         1     NONE   float       
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float       
// TEXCOORD                 6   xyz         4     NONE   float       
// TEXCOORD                 7   xyz         5     NONE   float   xyz 
// TEXCOORD                 8   xyzw        6     NONE   float   xy w
// TEXCOORD                 9   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v2.xyz
      dcl_input_ps linear v5.xyz
      dcl_input_ps linear v6.xyw
      dcl_output o0.xyzw
      dcl_temps 2
   0: dp3 r0.x, v2.xyzx, v2.xyzx
   1: rsq r0.x, r0.x
   2: mul r0.xyz, r0.xxxx, v2.xyzx
   3: dp3 r0.w, v5.xyzx, v5.xyzx
   4: rsq r0.w, r0.w
   5: mul r1.xyz, r0.wwww, v5.xyzx
   6: dp3_sat r0.x, r0.xyzx, r1.xyzx
   7: add r0.x, -r0.x, l(1.000000)
   8: log r0.x, r0.x
   9: mul r0.x, r0.x, l(7.000000)
  10: exp r0.x, r0.x
  11: div r0.yz, v6.xxyx, v6.wwww
  12: sample r1.xyzw, r0.yzyy, t0.xyzw, s0
  13: mad o0.xyz, r0.xxxx, l(1.222693, 0.000000, 3.679245, 0.000000), r1.xyzx
  14: mov o0.w, l(1.000000)
  15: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 39 math
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "QUEUE"="Geometry+0" "RenderType"="Opaque" "RenderPipeline"="LightweightPipeline" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
No keywords set in this variant.
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 39 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (32 bytes) on slot 0 {
  Vector4 _ShadowBias at 0
  Vector3 _LightDirection at 16
}
Constant Buffer "UnityPerCamera" (144 bytes) on slot 1 {
  Vector3 _WorldSpaceCameraPos at 64
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (416 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 304
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// TEXCOORD                 3   xyz         2     NONE   float   xyz 
// TEXCOORD                 4   xyz         3     NONE   float   xyz 
// TEXCOORD                 5   xyz         4     NONE   float   xyz 
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
// TEXCOORD                 7   xyz         6     NONE   float   xyz 
// TEXCOORD                 8   xyzw        7     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[2], immediateIndexed
      dcl_constantbuffer CB1[5], immediateIndexed
      dcl_constantbuffer CB2[8], immediateIndexed
      dcl_constantbuffer CB3[23], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o1.xyzw, position
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyz
      dcl_output o7.xyzw
      dcl_temps 3
   0: mul r0.xyz, v0.yyyy, cb2[1].xyzx
   1: mad r0.xyz, cb2[0].xyzx, v0.xxxx, r0.xyzx
   2: mad r0.xyz, cb2[2].xyzx, v0.zzzz, r0.xyzx
   3: mad r1.xyz, cb2[3].xyzx, v0.wwww, r0.xyzx
   4: add r0.xyz, r0.xyzx, cb2[3].xyzx
   5: add o6.xyz, -r0.xyzx, cb1[4].xyzx
   6: mul r0.xyz, r1.yyyy, cb2[5].xyzx
   7: mad r0.xyz, cb2[4].xyzx, r1.xxxx, r0.xyzx
   8: mad r0.xyz, cb2[6].xyzx, r1.zzzz, r0.xyzx
   9: mov o2.xyz, r1.xyzx
  10: add r0.xyz, r0.xyzx, cb2[7].xyzx
  11: mul r1.xyz, r0.yyyy, cb2[1].xyzx
  12: mad r0.xyw, cb2[0].xyxz, r0.xxxx, r1.xyxz
  13: mad r0.xyz, cb2[2].xyzx, r0.zzzz, r0.xywx
  14: add r0.xyz, r0.xyzx, cb2[3].xyzx
  15: dp3 r1.x, v1.xyzx, cb2[4].xyzx
  16: dp3 r1.y, v1.xyzx, cb2[5].xyzx
  17: dp3 r1.z, v1.xyzx, cb2[6].xyzx
  18: dp3 r0.w, r1.xyzx, r1.xyzx
  19: rsq r0.w, r0.w
  20: mul r1.xyz, r0.wwww, r1.xyzx
  21: dp3_sat r0.w, cb0[1].xyzx, r1.xyzx
  22: add r0.w, -r0.w, l(1.000000)
  23: mul r0.w, r0.w, cb0[0].y
  24: mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
  25: mul r2.xyzw, r0.yyyy, cb3[20].xyzw
  26: mad r2.xyzw, cb3[19].xyzw, r0.xxxx, r2.xyzw
  27: mad r0.xyzw, cb3[21].xyzw, r0.zzzz, r2.xyzw
  28: add r0.xyzw, r0.xyzw, cb3[22].xyzw
  29: add r0.z, r0.z, cb0[0].x
  30: min o1.z, r0.w, r0.z
  31: mov o1.xyw, r0.xyxw
  32: mov o3.xyz, r1.xyzx
  33: mul r0.xyz, v2.yyyy, cb2[1].xyzx
  34: mad r0.xyz, cb2[0].xyzx, v2.xxxx, r0.xyzx
  35: mad r0.xyz, cb2[2].xyzx, v2.zzzz, r0.xyzx
  36: dp3 r0.w, r0.xyzx, r0.xyzx
  37: rsq r0.w, r0.w
  38: mul r0.xyz, r0.wwww, r0.xyzx
  39: mov o4.xyz, r0.xyzx
  40: mul r2.xyz, r0.yzxy, r1.zxyz
  41: mad r0.xyz, r1.yzxy, r0.zxyz, -r2.xyzx
  42: mul o5.xyz, r0.xyzx, v2.wwww
  43: mov o7.xyzw, v3.xyzw
  44: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float       
// TEXCOORD                 3   xyz         2     NONE   float       
// TEXCOORD                 4   xyz         3     NONE   float       
// TEXCOORD                 5   xyz         4     NONE   float       
// TEXCOORD                 6   xyz         5     NONE   float       
// TEXCOORD                 7   xyz         6     NONE   float       
// TEXCOORD                 8   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 33 math
 Pass {
  Name "DepthOnly"
  Tags { "LIGHTMODE"="DepthOnly" "QUEUE"="Geometry+0" "RenderType"="Opaque" "RenderPipeline"="LightweightPipeline" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
No keywords set in this variant.
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 33 math, 3 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "Color"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"

Constant Buffer "UnityPerCamera" (144 bytes) on slot 0 {
  Vector3 _WorldSpaceCameraPos at 64
}
Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (416 bytes) on slot 2 {
  Matrix4x4 unity_MatrixVP at 304
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
// TEXCOORD                 3   xyz         2     NONE   float   xyz 
// TEXCOORD                 4   xyz         3     NONE   float   xyz 
// TEXCOORD                 5   xyz         4     NONE   float   xyz 
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
// TEXCOORD                 7   xyz         6     NONE   float   xyz 
// TEXCOORD                 8   xyzw        7     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[5], immediateIndexed
      dcl_constantbuffer CB1[8], immediateIndexed
      dcl_constantbuffer CB2[23], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xyz
      dcl_input v2.xyzw
      dcl_input v3.xyzw
      dcl_output o0.xy
      dcl_output_siv o1.xyzw, position
      dcl_output o2.xyz
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyz
      dcl_output o6.xyz
      dcl_output o7.xyzw
      dcl_temps 3
   0: mov o0.xy, l(0,0,0,0)
   1: mul r0.xyz, v0.yyyy, cb1[1].xyzx
   2: mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
   3: mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
   4: mad r1.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
   5: add r0.xyz, r0.xyzx, cb1[3].xyzx
   6: add o6.xyz, -r0.xyzx, cb0[4].xyzx
   7: mul r0.xyz, r1.yyyy, cb1[5].xyzx
   8: mad r0.xyz, cb1[4].xyzx, r1.xxxx, r0.xyzx
   9: mad r0.xyz, cb1[6].xyzx, r1.zzzz, r0.xyzx
  10: mov o2.xyz, r1.xyzx
  11: add r0.xyz, r0.xyzx, cb1[7].xyzx
  12: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
  13: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
  14: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
  15: add r0.xyzw, r0.xyzw, cb1[3].xyzw
  16: mul r1.xyzw, r0.yyyy, cb2[20].xyzw
  17: mad r1.xyzw, cb2[19].xyzw, r0.xxxx, r1.xyzw
  18: mad r1.xyzw, cb2[21].xyzw, r0.zzzz, r1.xyzw
  19: mad o1.xyzw, cb2[22].xyzw, r0.wwww, r1.xyzw
  20: dp3 r0.x, v1.xyzx, cb1[4].xyzx
  21: dp3 r0.y, v1.xyzx, cb1[5].xyzx
  22: dp3 r0.z, v1.xyzx, cb1[6].xyzx
  23: dp3 r0.w, r0.xyzx, r0.xyzx
  24: rsq r0.w, r0.w
  25: mul r0.xyz, r0.wwww, r0.xyzx
  26: mov o3.xyz, r0.xyzx
  27: mul r1.xyz, v2.yyyy, cb1[1].xyzx
  28: mad r1.xyz, cb1[0].xyzx, v2.xxxx, r1.xyzx
  29: mad r1.xyz, cb1[2].xyzx, v2.zzzz, r1.xyzx
  30: dp3 r0.w, r1.xyzx, r1.xyzx
  31: rsq r0.w, r0.w
  32: mul r1.xyz, r0.wwww, r1.xyzx
  33: mov o4.xyz, r1.xyzx
  34: mul r2.xyz, r0.zxyz, r1.yzxy
  35: mad r0.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
  36: mul o5.xyz, r0.xyzx, v2.wwww
  37: mov o7.xyzw, v3.xyzw
  38: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float       
// TEXCOORD                 3   xyz         2     NONE   float       
// TEXCOORD                 4   xyz         3     NONE   float       
// TEXCOORD                 5   xyz         4     NONE   float       
// TEXCOORD                 6   xyz         5     NONE   float       
// TEXCOORD                 7   xyz         6     NONE   float       
// TEXCOORD                 8   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }
}
Fallback "Hidden/InternalErrorShader"
}